import { builtinModules } from "node:module";
import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { defineConfig } from "vite";
import { svelte } from "@sveltejs/vite-plugin-svelte";
import { sveltePreprocess } from "svelte-preprocess";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/`;

const external = [
	"obsidian",
	"electron",
	"@codemirror/autocomplete",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/view",
	"@lezer/common",
	"@lezer/highlight",
	"@lezer/lr",
	...builtinModules,
];

export default defineConfig(({ mode }) => {
	const production = mode === "production";
	const outputDir = ".vite-build";

	return {
		plugins: [
			svelte({
				compilerOptions: {
					css: "injected",
				},
				preprocess: sveltePreprocess(),
			}),
			{
				name: "copy-obsidian-bundle",
				async writeBundle(_options, bundle) {
					const entry = bundle["main.js"];

					if (!entry || entry.type !== "chunk") {
						return;
					}

					await mkdir(resolve("."), { recursive: true });
					await writeFile(resolve("main.js"), entry.code);
				},
			},
		],
		build: {
			emptyOutDir: true,
			lib: {
				entry: "src/main.ts",
				formats: ["cjs"],
				fileName: () => "main.js",
			},
			minify: production,
			outDir: outputDir,
			sourcemap: production ? false : "inline",
			target: "es2018",
			watch: production ? null : {},
			rollupOptions: {
				external,
				output: {
					banner,
					entryFileNames: "main.js",
					exports: "default",
					format: "cjs",
					inlineDynamicImports: true,
				},
			},
		},
	};
});