import { builtinModules } from "node:module";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { defineConfig } from "vite";
import tailwindcss from "@tailwindcss/vite";
import { svelte } from "@sveltejs/vite-plugin-svelte";
import { sveltePreprocess } from "svelte-preprocess";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/`;

const external = [
	"obsidian",
	"electron",
	"@codemirror/autocomplete",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/view",
	"@lezer/common",
	"@lezer/highlight",
	"@lezer/lr",
	...builtinModules,
];

async function writeIfChanged(filePath: string, content: string): Promise<void> {
    try {
        const current = await readFile(filePath, "utf8");
        if (current === content) {
            return;
        }
    } catch {
        // File does not exist yet, proceed to write.
    }

    await writeFile(filePath, content);
}

export default defineConfig(({ mode }) => {
	const production = mode === "production";
	const outputDir = ".vite-build";

	return {
		plugins: [
            tailwindcss(),
			svelte({
				compilerOptions: {
					css: "injected",
				},
				preprocess: sveltePreprocess(),
			}),
			{
				name: "copy-obsidian-bundle",
				async writeBundle(_options, bundle) {
					const entry = bundle["main.js"];
                    const styles = bundle["styles.css"];

					if (!entry || entry.type !== "chunk") {
						return;
					}

					await mkdir(resolve("."), { recursive: true });
                    await writeIfChanged(resolve("main.js"), entry.code);

                    if (styles && styles.type === "asset") {
                        const css =
                            typeof styles.source === "string"
                                ? styles.source
                                : Buffer.from(styles.source).toString("utf8");
                        await writeIfChanged(resolve("styles.css"), css);
                    }
				},
			},
		],
		build: {
            cssCodeSplit: false,
			emptyOutDir: true,
			lib: {
                cssFileName: "styles",
				entry: "src/main.ts",
				formats: ["cjs"],
				fileName: () => "main.js",
			},
			minify: production,
			outDir: outputDir,
			sourcemap: production ? false : "inline",
            target: "es2022",
            watch: production
                ? null
                : {
                    exclude: ["main.js", "styles.css", ".vite-build/**"],
                },
            assetsDir: ".",
			rollupOptions: {
				external,
				output: {
					banner,
                    entryFileNames: "main.js",
                    assetFileNames: "styles.css",
					exports: "default",
					format: "cjs",
					inlineDynamicImports: true,
				},
			},
		},
        resolve: {
            alias: {
                $lib: resolve("./src/lib"),
            },
        },
	};
});